#if !canImport(ObjectiveC)
import XCTest

extension Publisher_ValidateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Publisher_ValidateTests = [
        ("testValidation", testValidation),
        ("testValidationFailure", testValidationFailure),
    ]
}

extension URLEndpointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLEndpointTests = [
        ("testHappyPath", testHappyPath),
        ("testResponseDecodingFailure", testResponseDecodingFailure),
        ("testResponseValidationFailure", testResponseValidationFailure),
        ("testURLRequestCreationFailure", testURLRequestCreationFailure),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Publisher_ValidateTests.__allTests__Publisher_ValidateTests),
        testCase(URLEndpointTests.__allTests__URLEndpointTests),
    ]
}
#endif
